export enum RelationshipType {
  FEATURES = "features",
  TEACHES = "teaches",
  INTRODUCES = "introduces",
  REPRESENTS = "represents",
  RELATED_TO = "related_to",
  DEPENDS_ON = "depends_on",
  PRECEDES = "precedes",
  FOLLOWS = "follows",
  CONTAINS = "contains",
  LOCATED_IN = "located_in",
  BELONGS_TO = "belongs_to",
  MENTORS = "mentors",
  ALLIES_WITH = "allies_with",
  OPPOSES = "opposes",
  USES = "uses",
  CREATED_BY = "created_by",
  APPEARS_IN = "appears_in",
  REQUIRES = "requires",
}
