"""Generated Numeria character."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class GeneratedCharacter:
    """Structured character generated by Forge."""

    name: str

    mathematical_concept: str

    description: str

    personality: str

    superpower: str

    weakness: str

    catchphrase: str
